services:
  - type: web
    name: d-web-care-api
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://pperrin:Miracoolix74%21@cluster0.psftbjl.mongodb.net/d-web-care?retryWrites=true&w=majority
